dataset_name: magnatagatune
data_dir: /gpfs/projects/upf97/downstream_datasets/magnatagatune/ # audio dir
gt_path: /gpfs/projects/upf97/downstream_datasets/magnatagatune/metadata/annotations_final.csv
output_dir: /gpfs/scratch/upf97/embeddings/ # TODO embeddings dir

splits:
  train_filelist: "/home/upf/upf455198/ssl-mtg/data/magnatagatune/train.txt"
  val_filelist: "/home/upf/upf455198/ssl-mtg/data/magnatagatune/validation.txt"
  test_filelist: "/home/upf/upf455198/ssl-mtg/data/magnatagatune/test.txt"

# Embedding extraction with the SSL model
predict:
  audio:
    file_format: mp3
    orig_freq: 16000
    new_freq: 16000
    mono: True
    half_precision: True
    num_workers: 20
  embedding_layer: [-1]
  device:
    accelerator: gpu
    devices: 1
    precision: bf16-mixed # TODO read from train config

# Probe configuration
probe:
  data_loader:
    batch_size: 256
    num_workers: 10
  embedding_processing:
    layer_aggregation: mean
    granularity: chunk
    time_aggregation: mean
  model:
    in_features: 768
    num_labels: 188
    hidden_size: 512
    num_layers: 2
    activation: relu
  trainer:
    accelerator: gpu
    devices: 1
    log_every_n_steps: 10
    max_epochs: 20
    num_sanity_val_steps: 0

# # Evaluation metrics for the task
# metrics:
#   - map_per_class
#   - roc_auc_per_class