dataset_name: magnatagatune
data_dir: /gpfs/projects/upf97/downstream_datasets/magnatagatune/
output_dir: /gpfs/scratch/upf97/embeddings/

# Embedding extraction with the SSL model
predict:
  audio:
    file_format: mp3
    orig_freq: 16000
    new_freq: 16000
    mono: True
    half_precision: True
    num_workers: 20
  embedding_layer: [-1]
  device:
    accelerator: gpu
    devices: 1
    precision: bf16-mixed # TODO read from train config

# Probe configuration
probe_model:
  dataloader:
    batch_size: 64
    num_workers: 20
    half_precision: True
    num_classes: 50
    num_features: 128
  embedding_aggregation:
    pooling: mean
  model:
    num_layers: 3
    hidden_size: 512
    dropout: 0.5
    pooling: mean
    embedding_size: 128
    device:
      accelerator: gpu
      devices: 1

# Evaluation metrics for the task
metrics:
  - map_per_class
  - roc_auc_per_class