[project]
version = "0.0"
name = "ssl-mtg"

requires-python = ">= 3.8"

dependencies = [
  "lightning~=2.2",
  "torch~=2.3",
  "gin-config~=0.5",
  "torchvision~=0.18",
  "wandb",
  "torchaudio",
  "matplotlib",
  "bayesian_optimization~=1.5.1",
  "scikit_learn~=1.5.2",
  "scipy~=1.14.1",
]

[project.optional-dependencies]
dev = [
    "ruff",
]

