[project]
version = "0.1"
name = "ssl-mtg"

requires-python = ">= 3.10"

dependencies = [
    "lightning==2.3",
    "torch==2.3",
    "gin-config~=0.5",
    "torchaudio==2.3",
    "torchvision==0.18",
    "wandb",
    "einops",
    "transformers"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "matplotlib",
    "bayesian_optimization~=1.5.1",
    "scikit_learn~=1.5.2",
    "scipy~=1.14.1",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
