dataset_name: "magnatagatune"
data_dir: "/gpfs/projects/upf97/downstream_datasets/magnatagatune/" # audio dir
gt_path: "/gpfs/projects/upf97/downstream_datasets/magnatagatune/metadata/mtat/binary.npy"
output_dir: "/gpfs/scratch/upf97/embeddings/" # TODO embeddings dir

splits:
  train_filelist: "/gpfs/projects/upf97/downstream_datasets/magnatagatune/metadata/mtat/train.npy"
  val_filelist: "/gpfs/projects/upf97/downstream_datasets/magnatagatune/metadata/mtat/valid.npy"
  test_filelist: "/gpfs/projects/upf97/downstream_datasets/magnatagatune/metadata/mtat/test.npy"

# Embedding extraction with the SSL model
predict:
  audio:
    file_format: "mp3"
    orig_freq: 16000
    new_freq: 16000
    mono: True
    half_precision: True
    num_workers: 20
  embedding_layer: [-1]
  device:
    accelerator: "gpu"
    devices: 1
    precision: "bf16-mixed" # TODO read from train config

# Probe configuration
probe:
  wandb_params:
    project: "magnatagatune"
    offline: True
    entity: "mtg-upf"
    save_dir: "/gpfs/projects/upf97/logs/"
  data_loader:
    batch_size: 256
    num_workers: 10
  embedding_processing:
    layer_aggregation: "none"
    granularity: "chunk"
    time_aggregation: "mean"
  model:
    hidden_size: 512
    num_layers: 2
    activation: "relu"
    num_labels: 50
    lr: 0.0001
  trainer:
    accelerator: "gpu"
    devices: 1
    log_every_n_steps: 10
    max_epochs: 20
    num_sanity_val_steps: 0